"""GitHub API client for repository management."""

import logging
from typing import Optional

import httpx

from src.config import settings

logger = logging.getLogger(__name__)

GITHUB_API_URL = "https://api.github.com"


def _get_headers() -> dict:
    """Get authorization headers."""
    return {
        "Authorization": f"token {settings.github_token}",
        "Accept": "application/vnd.github.v3+json",
    }


def _make_request(
    method: str,
    endpoint: str,
    json_data: Optional[dict] = None,
) -> dict:
    """Make a request to GitHub API."""
    if not settings.github_token:
        logger.warning("GITHUB_TOKEN not configured")
        return {}

    url = f"{GITHUB_API_URL}{endpoint}"

    with httpx.Client(timeout=30.0) as client:
        if method == "GET":
            response = client.get(url, headers=_get_headers())
        elif method == "POST":
            response = client.post(url, headers=_get_headers(), json=json_data)
        elif method == "PUT":
            response = client.put(url, headers=_get_headers(), json=json_data)
        elif method == "PATCH":
            response = client.patch(url, headers=_get_headers(), json=json_data)
        else:
            raise ValueError(f"Unsupported method: {method}")

        response.raise_for_status()
        return response.json() if response.content else {}


def create_repository(
    name: str,
    description: str = "",
    private: bool = True,
) -> dict:
    """Create a new repository."""
    data = {
        "name": name,
        "description": description,
        "private": private,
        "auto_init": True,
    }

    return _make_request("POST", "/user/repos", data)


def create_file(
    owner: str,
    repo: str,
    path: str,
    content: str,
    message: str = "Auto-generated by Vineyard Factory",
    branch: str = "main",
) -> dict:
    """Create or update a file in a repository."""
    import base64

    data = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch": branch,
    }

    # Check if file exists to get SHA
    try:
        existing = _make_request("GET", f"/repos/{owner}/{repo}/contents/{path}")
        if existing.get("sha"):
            data["sha"] = existing["sha"]
    except Exception:
        pass

    return _make_request("PUT", f"/repos/{owner}/{repo}/contents/{path}", data)


def create_files_batch(
    owner: str,
    repo: str,
    files: list[dict],
    branch: str = "main",
) -> list[str]:
    """Create multiple files in a repository."""
    created_paths = []

    for file in files:
        try:
            result = create_file(
                owner=owner,
                repo=repo,
                path=file.get("path", ""),
                content=file.get("content", ""),
                message=file.get("message", "Auto-generated"),
                branch=branch,
            )
            if result:
                created_paths.append(file.get("path", ""))
        except Exception as e:
            logger.error(f"Failed to create file {file.get('path')}: {e}")

    return created_paths


def create_pull_request(
    owner: str,
    repo: str,
    title: str,
    body: str,
    head: str,
    base: str = "main",
) -> dict:
    """Create a pull request."""
    data = {
        "title": title,
        "body": body,
        "head": head,
        "base": base,
    }

    return _make_request("POST", f"/repos/{owner}/{repo}/pulls", data)


def get_repository(owner: str, repo: str) -> dict:
    """Get repository details."""
    return _make_request("GET", f"/repos/{owner}/{repo}")


def create_branch(
    owner: str,
    repo: str,
    branch_name: str,
    from_branch: str = "main",
) -> dict:
    """Create a new branch."""
    # Get SHA of source branch
    ref = _make_request("GET", f"/repos/{owner}/{repo}/git/refs/heads/{from_branch}")
    sha = ref.get("object", {}).get("sha")

    if not sha:
        raise ValueError(f"Could not find SHA for branch {from_branch}")

    data = {
        "ref": f"refs/heads/{branch_name}",
        "sha": sha,
    }

    return _make_request("POST", f"/repos/{owner}/{repo}/git/refs", data)
